ARG NODE_VERSION
FROM node:${NODE_VERSION}-alpine

# Install required packages
RUN apk update && apk add --no-cache build-base python3 docker-cli docker-cli-buildx docker-compose

WORKDIR /src

# Install client dependencies
COPY Client/package.json Client/package.json
RUN cd Client && npm install

COPY Client Client

WORKDIR /src/Client

ENTRYPOINT ["npm", "start"]

EXPOSE 3000
